<a href="https://colab.research.google.com/github/thanadolch/KKU_data_mining/blob/master/data103Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## numpy array

In [2]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [3]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [4]:
np2.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [5]:
np2[0,:]

array([1, 2])

#HW 6 สร้าง Distance metrix (Euclidean) ของ np2
โดยสร้าง function สำหรับคำนวณ Manhattan Distance และ Euclidean Distance

'''' def Euclident(data1,data2): 
    # process
return dist
''''''

In [6]:
import math

In [7]:
def Manhattan(data1,data2):
    distX = abs(data1[0]-data2[0])
    distY = abs(data1[1]-data2[1])
    return distX+distY

In [8]:
Manhattan(np2[0,:],np2[1,:])

5

In [9]:
dist_math = np.zeros((4,4))
dist_math 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
for i in range(4):
    for j in range(4):
        dist_math[i,j] = Manhattan(np2[i,:],np2[j,:])
dist_math

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [11]:
def Euclidean(data1,data2):
    distX = pow(abs(data1[0]-data2[0]),2)
    distY = pow(abs(data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [12]:
dist_math1 = np.zeros((4,4))
dist_math1 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j] = Euclidean(np2[i,:],np2[j,:])
dist_math1

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

#Distance of norminal or categorical features

### (extra) Phyton data structure (Dictoionary)


In [14]:
d_A = {'a':1,2:3,3:5,'cat':6}

In [15]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [16]:
d_A['cat']

6

In [17]:
d_A['dog'] = [1,2,3,4,5]

In [18]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [19]:
import pandas as pd

In [20]:
data_dict = {'color' :['red','red','green'],
             'status':['single','married','single']}
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

In [21]:
data_pd = pd.DataFrame.from_dict(data_dict)
data_pd

color   status
0    red   single
1    red  married
2  green   single

#Categorical feature distance method#1

In [22]:
list(data_pd.iloc[0,:])

['red', 'single']

In [23]:
def meth1_dist(data1,data2):
    N = 0
    print(f'data1 is {data1} and data2 is {data2}')
    for i in range(len(data1)):
      if data1[i] != data2[i]:
          N = N+1
    return N/len(data1)

In [24]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

data1 is ['red', 'single'] and data2 is ['red', 'married']


0.5

#HW7 Calculate distance matrix of data_pd using meth1_dist()

In [28]:
dist_math2 = np.zeros((3,3))
dist_math2 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
for i in range(3):
    for j in range(3):
        dist_math2[i,j] = meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))
dist_math2

data1 is ['red', 'single'] and data2 is ['red', 'married']
data1 is ['red', 'single'] and data2 is ['red', 'married']
data1 is ['red', 'single'] and data2 is ['red', 'married']
data1 is ['red', 'single'] and data2 is ['red', 'married']
data1 is ['red', 'single'] and data2 is ['red', 'married']
data1 is ['red', 'single'] and data2 is ['red', 'married']
data1 is ['red', 'single'] and data2 is ['red', 'married']
data1 is ['red', 'single'] and data2 is ['red', 'married']
data1 is ['red', 'single'] and data2 is ['red', 'married']


array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

## Categorical feature distance method#2

In [25]:
data_pd_binary = pd.get_dummies(data_pd)
data_pd_binary

color_green  color_red  status_married  status_single
0            0          1               0              1
1            0          1               1              0
2            1          0               0              1

In [26]:
def binary_sym_dist(data1,data2):
    q = 0
    rs = 0
    t = 0
    for i in range(len(data1)):
        if data1[i] == data2[i]:
            if data1[i] == 1:
               q = q + 1
            else:
                t = t + 1
        if data1[i] != data2[i]:
            rs = rs + 1    
    return (rs)/(q+rs+t)

In [44]:
binary_sym_dist(list(data_pd_binary.iloc[0,:]),list(data_pd_binary.iloc[1,:]))

0.5

#HW8 calculate distance matrix of data_pd_binary using binary_sym_dist()

In [37]:
binary_sym_dist1 = np.zeros((3,3))
binary_sym_dist1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
for i in range(3):
    for j in range(3):
        binary_sym_dist1[i,j] = binary_sym_dist(list(data_pd_binary.iloc[0,:]),list(data_pd_binary.iloc[1,:]))
binary_sym_dist1

TypeError: ignored